### PR TITLE
Relative layout support for creating pdf.

### PR DESCRIPTION
**Pull request by santosh-kumar-kaushal**
Hi @tejpratap46,
Can you please check and approve the PR, this PR includes changes for relative layout support.
Thanks

### CODE REVIEW

**Comment by tejpratap46** [comment]
Can you suggest an example where a `ReleativeLayout` would be better instead of a `LinearLayout`.
`LinearLayout` are easier to nest programmatically and hence less room for error.

If you have some situation where `LinearLayout` cannot do the job then adding `RelativeLayout` would be a better addition rather than just a Good-To-Have feature.

By the way, thank you for PR.

**Comment by santosh-kumar-kaushal** [comment]
> Can you suggest an example where a `ReleativeLayout` would be better instead of a `LinearLayout`.
> `LinearLayout` are easier to nest programmatically and hence less room for error.
> 
> If you have some situation where `LinearLayout` cannot do the job then adding `RelativeLayout` would be a better addition rather than just a Good-To-Have feature.
> 
> By the way, thank you for PR.

Thanks for the question, with `Linear layout` we don't have flexibility to align the views on top of some other view, It can either work **horizontally/ vertically** but in case we want to keep a view on top of a view `Relative layout` is flexible. we can take a specific case where we want to write something on Image, `Linear layout` won't be able to do it but Yes, `Relative` can. Now with `Relative layout` addition we will be able to keep an image in background and write something on top of that something like **watermark**. Hope this example clarifies the need of `Relative layout`. 

Example

```
PDFVerticalView pdfVerticalView = new PDFVerticalView(getApplicationContext());
        PDFRelativeView pdfRelativeView=new PDFRelativeView(getApplicationContext());
        PDFImageView imageView = new PDFImageView(getApplicationContext());
        LinearLayout.LayoutParams imageLayoutParam = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                600);
        imageView.setImageScale(ImageView.ScaleType.FIT_CENTER);
        imageView.setImageResource(R.drawable.watermark);
        imageView.setLayout(imageLayoutParam);
        pdfRelativeView.addView(imageView);

        PDFTextView routingNumber=new PDFTextView(getApplicationContext(),PDFTextView.PDF_TEXT_SIZE.H1);
        SpannableString routingNumberText = new SpannableString("0000000000");
        RelativeLayout.LayoutParams routingNumberLayoutParams=new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);
        routingNumberLayoutParams.setMargins(30,TEXT_MARGIN_TOP,0,0);
        routingNumber.setLayout(routingNumberLayoutParams);
        routingNumberText.setSpan(new ForegroundColorSpan(Color.BLUE), 0, routingNumberText.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
        routingNumber.setText(routingNumberText);
        pdfRelativeView.addView(routingNumber);

        PDFTextView accountNumber=new PDFTextView(getApplicationContext(),PDFTextView.PDF_TEXT_SIZE.H1);
        SpannableString accountNumberText = new SpannableString("0000000000");
        RelativeLayout.LayoutParams accountNumberLayoutParams=new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);
        accountNumberLayoutParams.setMargins(185,TEXT_MARGIN_TOP,0,0);
        accountNumber.setLayout(accountNumberLayoutParams);
        accountNumberText.setSpan(new ForegroundColorSpan(Color.BLUE), 0, accountNumberText.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
        accountNumber.setText(accountNumberText);
        pdfRelativeView.addView(accountNumber);

        PDFTextView checking=new PDFTextView(getApplicationContext(),PDFTextView.PDF_TEXT_SIZE.H1);
        SpannableString checkingText = new SpannableString("Some text");
        RelativeLayout.LayoutParams checkingTextLayoutParams=new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);
        checkingTextLayoutParams.setMargins(365,TEXT_MARGIN_TOP,0,0);
        checking.setLayout(checkingTextLayoutParams);
        checkingText.setSpan(new ForegroundColorSpan(Color.BLUE), 0, checkingText.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
        checking.setText(checkingText);
        pdfRelativeView.addView(checking);

        pdfVerticalView.addView(pdfRelativeView);
```

**Comment by tejpratap46** [comment]
I can see your point, and people do have need to add watermark on PDF's.

I tested your PR and here are my thoughts.
But the way you are trying to achieve it will fail if you add a lot of data inside one `RelativeView` as the library will not be able to paginate views (separate views in multiple pages). You might not have needed multiple pages in your application, but if you did, you can see it trimming content after 1 page.

To do it correctly, we need an overridden method `protected PDFFrameLayout/PDFImageView getWatermarkView(int forPage)` and before creating new page, add this frame and then overlap it with our `PDFBody`.

And also i think `RelativeLayout` would be overkill for just adding one view over another, `FrameLayout` would be better choice or that. (it also has better performance than RelativeLayout)

Thank you for your PR and suggesting, i will be adding the ability to add watermark for every page as we add header and footer.

**Comment by tejpratap46** [comment]
#14 Added issue to track progress, closing PR

**Pull request closed without merging**
